src/Web/Pages/Basket/Checkout.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Sula.Shipment.ApplicationCore.Entities.OrderAggregate;
using Sula.Shipment.ApplicationCore.Exceptions;
using Sula.Shipment.ApplicationCore.Interfaces;
using Sula.Shipment.Infrastructure.Identity;
using Sula.Shipment.Web.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sula.Shipment.Web.Pages.Basket
{
    [Authorize]
    public class CheckoutModel : PageModel
    {
        private readonly IBasketService _basketService;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IOrderService _orderService;
        private string _username = null;
        private readonly IBasketViewModelService _basketViewModelService;
        private readonly IAppLogger<CheckoutModel> _logger;

        public CheckoutModel(IBasketService basketService,
            IBasketViewModelService basketViewModelService,
            SignInManager<ApplicationUser> signInManager,
            IOrderService orderService,
            IAppLogger<CheckoutModel> logger)
        {
            _basketService = basketService;
            _signInManager = signInManager;
            _orderService = orderService;
            _basketViewModelService = basketViewModelService;
            _logger = logger;
        }

        public BasketViewModel BasketModel { get; set; } = new BasketViewModel();

        public async Task OnGet()
        {
            await SetBasketModelAsync();
        }

        public async Task<IActionResult> OnPost(IEnumerable<BasketItemViewModel> items)
        {
            try
            {
                await SetBasketModelAsync();

                if (!ModelState.IsValid)
                {
                    return BadRequest();
                }

                var updateModel = items.ToDictionary(b => b.Id.ToString(), b => b.Quantity);
                await _basketService.SetQuantities(BasketModel.Id, updateModel);
                await _orderService.CreateOrderAsync(BasketModel.Id, new Address(BasketModel.RecipientAddress, "", "", "", ""), BasketModel.CheckoutMethod, BasketModel.CourierArrivalTime, BasketModel.RecipientName, BasketModel.RecipientSurname, BasketModel.RecipientPhoneNo);
                await _basketService.DeleteBasketAsync(BasketModel.Id);               
            }
            catch (EmptyBasketOnCheckoutException emptyBasketOnCheckoutException)
            {
                //Redirect to Empty Basket page
                _logger.LogWarning(emptyBasketOnCheckoutException.Message);
                return RedirectToPage("/Basket/Index");
            }

            return RedirectToPage("Success");
        }

        private async Task SetBasketModelAsync()
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                BasketModel = await _basketViewModelService.GetOrCreateBasketForUser(User.Identity.Name);
            }
            else
            {
                GetOrSetBasketCookieAndUserName();
                BasketModel = await _basketViewModelService.GetOrCreateBasketForUser(_username);
            }
        }

        private void GetOrSetBasketCookieAndUserName()
        {
            if (Request.Cookies.ContainsKey(Constants.BASKET_COOKIENAME))
            {
                _username = Request.Cookies[Constants.BASKET_COOKIENAME];
            }
            if (_username != null) return;

            _username = Guid.NewGuid().ToString();
            var cookieOptions = new CookieOptions();
            cookieOptions.Expires = DateTime.Today.AddYears(10);
            Response.Cookies.Append(Constants.BASKET_COOKIENAME, _username, cookieOptions);
        }
    }
}

src/Web/Pages/Basket/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sula.Shipment.ApplicationCore.Interfaces;
using Sula.Shipment.Infrastructure.Identity;
using Sula.Shipment.Web.Interfaces;
using Sula.Shipment.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sula.Shipment.Web.Pages.Basket
{
    public class IndexModel : PageModel
    {
        public List<SelectListItem> CheckoutMethods = new List<SelectListItem>
        {
            new SelectListItem {Value = "Swedbank", Text = "Swedbank" },
            new SelectListItem {Value = "Luminor", Text = "Luminor" },
            new SelectListItem {Value = "Šiaulių bankas", Text = "Šiaulių bankas" },
            new SelectListItem {Value = "Citadele", Text = "Citadele" },
            new SelectListItem {Value = "Credit Card", Text = "Credit Card" }
        };

        private readonly IBasketService _basketService;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private string _username = null;
        private readonly IBasketViewModelService _basketViewModelService;

        public IndexModel(IBasketService basketService,
            IBasketViewModelService basketViewModelService,
            SignInManager<ApplicationUser> signInManager)
        {
            _basketService = basketService;
            _signInManager = signInManager;
            _basketViewModelService = basketViewModelService;
        }

        public BasketViewModel BasketModel { get; set; } = new BasketViewModel();

        public async Task OnGet()
        {
            await SetBasketModelAsync();
        }

        public async Task<IActionResult> OnPost(CatalogItemViewModel productDetails)
        {
            if (productDetails?.Id == null)
            {
                return RedirectToPage("/Index");
            }
            await SetBasketModelAsync();

            await _basketService.AddItemToBasket(BasketModel.Id, productDetails.Id, productDetails.Price);

            await SetBasketModelAsync();

            return RedirectToPage();
        }

        public async Task OnPostUpdate(IEnumerable<BasketItemViewModel> items, string checkoutMethod, string courierArrivalTime, string recipientName, string recipientSurname, string recipientAddress, string recipientPhoneNo)
        {
            await SetBasketModelAsync();

            if (!ModelState.IsValid)
            {
                return;
            }

            var updateModel = items.ToDictionary(b => b.Id.ToString(), b => b.Quantity);
            await _basketService.SetQuantities(BasketModel.Id, updateModel);
            await _basketService.SetCheckoutProperties(BasketModel.Id, checkoutMethod, courierArrivalTime, recipientName, recipientSurname, recipientAddress, recipientPhoneNo);

            await SetBasketModelAsync();
        }

        private async Task SetBasketModelAsync()
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                BasketModel = await _basketViewModelService.GetOrCreateBasketForUser(User.Identity.Name);
            }
            else
            {
                GetOrSetBasketCookieAndUserName();
                BasketModel = await _basketViewModelService.GetOrCreateBasketForUser(_username);
            }
        }

        private void GetOrSetBasketCookieAndUserName()
        {
            if (Request.Cookies.ContainsKey(Constants.BASKET_COOKIENAME))
            {
                _username = Request.Cookies[Constants.BASKET_COOKIENAME];
            }
            if (_username != null) return;

            _username = Guid.NewGuid().ToString();
            var cookieOptions = new CookieOptions { IsEssential = true };
            cookieOptions.Expires = DateTime.Today.AddYears(10);
            Response.Cookies.Append(Constants.BASKET_COOKIENAME, _username, cookieOptions);
        }
    }
}

src/Web/Pages/Basket/Success.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Sula.Shipment.Web.Pages.Basket
{
    [Authorize]
    public class SuccessModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/Web/Pages/Basket/Checkout.cshtml
@page
@model CheckoutModel
@{
    ViewData["Title"] = "Checkout";
}
<section class="esh-catalog-hero">
    <div class="container">
        <img class="esh-catalog-title" src="~/images/main_banner_text.png" />
    </div>
</section>

<div class="container">
    <h1>Review</h1>
    @if (Model.BasketModel.Items.Any())
    {
        <form asp-page="Checkout" method="post">
            <article class="esh-basket-titles row">
                <br />
                <section class="esh-basket-title col-xs-3">Product</section>
                <section class="esh-basket-title col-xs-3 hidden-lg-down"></section>
                <section class="esh-basket-title col-xs-2">Price</section>
                <section class="esh-basket-title col-xs-2">Quantity</section>
                <section class="esh-basket-title col-xs-2">Cost</section>
            </article>
            <div class="esh-catalog-items row">
                <div asp-validation-summary="All" class="text-danger"></div>
                @for (int i = 0; i < Model.BasketModel.Items.Count; i++)
                {
                    var item = Model.BasketModel.Items[i];
                    <article class="esh-basket-items row">
                        <div>
                            <section class="esh-basket-item esh-basket-item--middle col-lg-3 hidden-lg-down">
                                <img class="esh-basket-image" src="@item.PictureUrl" />
                            </section>
                            <section class="esh-basket-item esh-basket-item--middle col-xs-3">@item.ProductName</section>
                            <section class="esh-basket-item esh-basket-item--middle col-xs-2">$ @item.UnitPrice.ToString("N2")</section>
                            <section class="esh-basket-item esh-basket-item--middle col-xs-2">
                                <input type="hidden" name="@("Items[" + i + "].Id")" value="@item.Id" />
                                <input type="hidden" name="@("Items[" + i + "].Quantity")" value="@item.Quantity" />
                                @item.Quantity
                            </section>
                            <section class="esh-basket-item esh-basket-item--middle esh-basket-item--mark col-xs-2">$ @Math.Round(item.Quantity * item.UnitPrice, 2).ToString("N2")</section>
                        </div>
                        <div class="row">

                        </div>
                    </article>
                }

                <div class="container">
                    <article class="esh-basket-titles esh-basket-titles--clean row">
                        <section class="esh-basket-title col-xs-10"></section>
                        <section class="esh-basket-title col-xs-2">Total</section>
                    </article>

                    <article class="esh-basket-items row">
                        <section class="esh-basket-item col-xs-10"></section>
                        <section class="esh-basket-item esh-basket-item--mark col-xs-2">$ @Model.BasketModel.Total().ToString("N2")</section>
                    </article>

                    <article class="esh-basket-items row">
                        <section class="esh-basket-item col-xs-7"></section>
                    </article>
                </div>
                <div class="row" style="width: 50%">

                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.CheckoutMethod"></label>
                        <input readonly name="checkoutMethod" asp-for="@Model.BasketModel.CheckoutMethod" value="@Model.BasketModel.CheckoutMethod" class="form-control" />
                        <span asp-validation-for="@Model.BasketModel.CheckoutMethod" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.CourierArrivalTime"></label>
                        <input readonly name="courierArrivalTime" asp-for="@Model.BasketModel.CourierArrivalTime" value="@Model.BasketModel.CourierArrivalTime" class="form-control" />
                        <span asp-validation-for="@Model.BasketModel.CourierArrivalTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.RecipientName"></label>
                        <input readonly name="recipientName" asp-for="@Model.BasketModel.RecipientName" value="@Model.BasketModel.RecipientName" class="form-control" />
                        <span asp-validation-for="@Model.BasketModel.RecipientName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.RecipientSurname"></label>
                        <input readonly name="recipientSurname" asp-for="@Model.BasketModel.RecipientSurname" value="@Model.BasketModel.RecipientSurname" class="form-control" />
                        <span asp-validation-for="@Model.BasketModel.RecipientSurname" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.RecipientAddress"></label>
                        <input readonly name="recipientAddress" asp-for="@Model.BasketModel.RecipientAddress" value="@Model.BasketModel.RecipientAddress" class="form-control" />
                        <span asp-validation-for="@Model.BasketModel.RecipientAddress" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.RecipientPhoneNo"></label>
                        <input readonly name="recipientPhoneNo" asp-for="@Model.BasketModel.RecipientPhoneNo" value="@Model.BasketModel.RecipientPhoneNo" class="form-control" />
                        <span asp-validation-for="@Model.BasketModel.RecipientPhoneNo" class="text-danger"></span>
                    </div>

                </div>
                <div class="row">
                    <section class="esh-basket-item col-xs-1">
                        <a asp-page="Index" class="btn esh-basket-checkout text-white">[ Back ]</a>
                    </section>
                    <section class="esh-basket-item col-xs-push-7 col-xs-4 text-right">
                        <input type="submit" class="btn esh-basket-checkout" value="[ Pay Now ]" />
                    </section>
                </div>
            </div>
        </form>
    }
    else
    {
        <h3 class="esh-catalog-items row">
            Basket is empty.
        </h3>

        <section class="esh-basket-item">
            <a asp-page="/Index" class="btn esh-basket-checkout text-white">[ Continue Shopping..]</a>
        </section>
    }
</div>

src/Web/Pages/Basket/Index.cshtml
@page "{handler?}"
@model IndexModel
@{
    ViewData["Title"] = "Basket";
}
<section class="esh-catalog-hero">
    <div class="container">
        <img class="esh-catalog-title" src="~/images/main_banner_text.png" />
    </div>
</section>

<div class="container">

    @if (Model.BasketModel.Items.Any())
    {
        <form method="post">
            <article class="esh-basket-titles row">
                <br />
                <section class="esh-basket-title col-xs-3">Product</section>
                <section class="esh-basket-title col-xs-3 hidden-lg-down"></section>
                <section class="esh-basket-title col-xs-2">Price</section>
                <section class="esh-basket-title col-xs-2">Quantity</section>
                <section class="esh-basket-title col-xs-2">Cost</section>
            </article>
            <div class="esh-catalog-items row">
                <div asp-validation-summary="All" class="text-danger"></div>
                @for (int i = 0; i < Model.BasketModel.Items.Count; i++)
                {
                    var item = Model.BasketModel.Items[i];
                    <article class="esh-basket-items row">
                        <div>
                            <section class="esh-basket-item esh-basket-item--middle col-lg-3 hidden-lg-down">
                                <img class="esh-basket-image" src="@item.PictureUrl" />
                            </section>
                            <section class="esh-basket-item esh-basket-item--middle col-xs-3">@item.ProductName</section>
                            <section class="esh-basket-item esh-basket-item--middle col-xs-2">$ @item.UnitPrice.ToString("N2")</section>
                            <section class="esh-basket-item esh-basket-item--middle col-xs-2">
                                <input type="hidden" name="@("Items[" + i + "].Id")" value="@item.Id" />
                                <input type="number" class="esh-basket-input" min="0" name="@("Items[" + i + "].Quantity")" value="@item.Quantity" />
                            </section>
                            <section class="esh-basket-item esh-basket-item--middle esh-basket-item--mark col-xs-2">$ @Math.Round(item.Quantity * item.UnitPrice, 2).ToString("N2")</section>
                        </div>
                        <div class="row">

                        </div>
                    </article>
                }

                <div class="container">
                    <article class="esh-basket-titles esh-basket-titles--clean row">
                        <section class="esh-basket-title col-xs-10"></section>
                        <section class="esh-basket-title col-xs-2">Total</section>
                    </article>

                    <article class="esh-basket-items row">
                        <section class="esh-basket-item col-xs-10"></section>
                        <section class="esh-basket-item esh-basket-item--mark col-xs-2">$ @Model.BasketModel.Total().ToString("N2")</section>
                    </article>

                    <article class="esh-basket-items row">
                        <section class="esh-basket-item col-xs-7"></section>
                    </article>
                </div>
                <div class="row" style="width: 50%">
                    
                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.CheckoutMethod"></label>
                        <select asp-for="@Model.BasketModel.CheckoutMethod" asp-items="@Model.CheckoutMethods" name="checkoutMethod">
                            <option value="">Choose a checkout method</option>
                        </select>
                        <span asp-validation-for="@Model.BasketModel.CheckoutMethod" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.CourierArrivalTime"></label>
                        <input required name="courierArrivalTime" asp-for="@Model.BasketModel.CourierArrivalTime" value="@Model.BasketModel.CourierArrivalTime" class="form-control" />
                        <span asp-validation-for="@Model.BasketModel.CourierArrivalTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.RecipientName"></label>
                        <input required name="recipientName" asp-for="@Model.BasketModel.RecipientName" value="@Model.BasketModel.RecipientName" class="form-control" />
                        <span asp-validation-for="@Model.BasketModel.RecipientName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.RecipientSurname"></label>
                        <input required name="recipientSurname" asp-for="@Model.BasketModel.RecipientSurname" value="@Model.BasketModel.RecipientSurname" class="form-control" />
                        <span asp-validation-for="@Model.BasketModel.RecipientSurname" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.RecipientAddress"></label>
                        <input required name="recipientAddress" asp-for="@Model.BasketModel.RecipientAddress" value="@Model.BasketModel.RecipientAddress" class="form-control" />
                        <span asp-validation-for="@Model.BasketModel.RecipientAddress" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.BasketModel.RecipientPhoneNo"></label>
                        <input required name="recipientPhoneNo" asp-for="@Model.BasketModel.RecipientPhoneNo" value="@Model.BasketModel.RecipientPhoneNo" class="form-control" />
                        <span asp-validation-for="@Model.BasketModel.RecipientPhoneNo" class="text-danger"></span>
                    </div>

                </div>
                <div class="row">
                    <section class="esh-basket-item col-xs-1">
                        <a asp-page="/Index" class="btn esh-basket-checkout text-white">[ Continue Shopping..]</a>
                    </section>
                    <section class="esh-basket-item col-xs-push-7 col-xs-4">

                        <button class="btn esh-basket-checkout" name="updatebutton" value="" type="submit"
                                asp-page-handler="Update">
                            [ Update ]
                        </button>
                        <a asp-page="./Checkout" class="btn esh-basket-checkout">[ Checkout ]</a>
                    </section>
                </div>
            </div>
        </form>
    }
    else
    {
        <h3 class="esh-catalog-items row">
            Basket is empty.
        </h3>

        <section class="esh-basket-item">
            <a asp-page="/Index" class="btn esh-basket-checkout text-white">[ Continue Shopping..]</a>
        </section>
    }
</div>

src/Web/Pages/Basket/Success.cshtml
@page
@model SuccessModel
@{
    ViewData["Title"] = "Checkout Complete";
}

<section class="esh-catalog-hero">
    <div class="container">
        <img class="esh-catalog-title" src="~/images/main_banner_text.png" />
    </div>
</section>

<div class="container">
    <h1>Thanks for your Order!</h1>

    <a asp-page="/Index">Continue Shopping...</a>
</div>